name: Build and test game

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: pip install -r requirements.txt
      
    - name: Create directory
      run: |
        mkdir ~/DebugAPK
        mkdir Beta
    
    - name: Upload game
      uses: actions/upload-artifact@v2
      with:
        name: debug lol
        path: ~/DebugAPK/Beta
